name: test

on: workflow_dispatch

jobs:
  runner:
    runs-on: ubuntu_latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Run audit
        uses: DariaLeskavets/auditor_runner/.github/workflows/auditor-runner.yml@add_action
        with:
          PORTAL_TOKEN: ${{ secrets.PORTAL_TOKEN }}
          PORTAL_URL: ${{ secrets.PORTAL_URL }}
